export enum DanceStyles {
    HIP_HOP = 'Hip-Hop',
    JAZZ = 'Jazz',
    CONTEMPORARY = 'Contemporary',
    BALLET = 'Ballet',
    TAP = 'Tap',
    FREE_STYLE = 'Freestyle',
    CLASSICAL = 'Classical',
    FOLK = ' Folk',
    BOLLYWOOD = 'Bollywood',
    Salsa = 'Salsa',
    KUCHIPUDI = 'Kuchipudi',
    ODISSI = 'Odissi',
    KATHAK = 'Kathak',
    MOHINIYATTAM = 'Mohiniyattam',
    BELLY_DANCE = 'Belly',
    LOCKING = 'Locking',
    POPPING = 'Popping',
    BHARATHANATYAM = 'BharathanatyaM',
    BREAKING = 'Breaking',
}